name: CI Workflow

# trigger
on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: "build"
    uses: ./.github/workflow/build.yml
    with:
      version: "8.3"
  test:
    name: "test"
    needs: [build]
    uses: ./.github/workflow/test.yml
    with:
      version: "8.3"
  

